### PR TITLE
fix: Ensure python command is set

### PR DESCRIPTION
**Pull request by Jaryt**
If python is not set, it will be aliased to python3

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:9512d39ffa38f903ff837ae4c94089dcf74f9c99

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:8960f83891a3ec2a190a1f0455764ba7debc6168

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:238996fb8bd935f7be33c1a21b3a43561b7e2341

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:8a2e4c0b6b0d24b1e01abfebcfc5a9d1bb3c9da0

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:85f0308f0494ef2bdd6db4ab7b15c41a01c14d18

**Review by brivu — APPROVED** [review]
Looks good!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:94e68ac873cfd31b35dc28178090285128cf2811

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:94e68ac873cfd31b35dc28178090285128cf2811

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=2.1.0

**Pull request merged**
