### PR TITLE
Update the directories required for cache so it works on windows

### LINKED ISSUE #123: install-packages caching fails on Windows
## Orb version:

```yaml
orbs:
  python: circleci/python@2.2.0
```

## What happened:

I'm writing a CircleCI build file that packages a python project on both Windows and Linux.
I have a job with a parameterise executor that calls `checkout` and then calls the `install-packages` command.

On [Linux](https://app.circleci.com/pipelines/github/i2group/ias-client/98/workflows/bf811bcd-6c0a-41e3-a73e-e8a208ccb4c7/jobs/191), the `install-packages` command's use of `restore_cache` & `save_cache` works fine:
image

On [Windows](https://app.circleci.com/pipelines/github/i2group/ias-client/98/workflows/bf811bcd-6c0a-41e3-a73e-e8a208ccb4c7/jobs/192), these steps are red with an error:
image
The "Restoring cache" step errors saying `error computing cache key: template: cacheKey:1:18: executing "cacheKey" at <checksum "/tmp/cci_pycache/lockfile">: error calling checksum: open C:\tmp\cci_pycache\lockfile: The system cannot find the path specified.`
The Saving cache" step errors saying `Error computing cache key: template: cacheKey:1:18: executing "cacheKey" at <checksum "/tmp/cci_pycache/lockfile">: error calling checksum: open C:\tmp\cci_pycache\lockfile: The system cannot find the path specified.`
... but the job continues, albeit without any caching functionality.

This lack of caching results in bad performance - it took 8 seconds on Linux (7 seconds to restore the cache and 1 to use it) but 49 seconds on Windows (45 seconds to re-download everything, 4 to use it)

## Expected behavior:

Caching should work (perfectly) on all OSs: CircleCI orbs should _not_ be Linux-specific.
While I would expect things might take longer on Windows than Linux, the Microsoft-performance-penalty is usually only "takes twice as long compared to Linux" whereas the lack of caching is making it take take *six* times as long ... and results in way more (reliance upon) network traffic (and hence build instability).

Also, ideally, I shouldn't have to switch the Windows agent's default shell to bash either.
As-is, the CircleCI Windows orb defaults all CircleCI Windows agents to use a default shell of Powershell, so either all `run` commands then have to specify bash, or users have to override the default when specifying the executor (which is what I've done here) ... or the Windows orb needs to change to default to bash (which would be a major breaking change, albeit maybe a welcome one).
So it would be nice if the python orb's bash `run` commands declared that they're bash commands so that a Windows machine doesn't try to run them as Powershell.

## Additional Information:

Heavily-trimmed CircleCI config.yml:
```yaml
version: 2.1

orbs:
  python: circleci/python@2
  windows: circleci/windows@5

executors:
  linux:
    docker:
      - image: cimg/python:3.12
    resource_class: small

commands:
  python-install-pipenv-packages:
    parameters:
      app-dir:
        type: string
    steps:
      - python/install-packages:
          app-dir: <<parameters.app-dir>>
          pkg-manager: pipenv
          include-branch-in-cache-key: false
          args: --dev
  install-python-on-windows:
    steps:
      - run:
          name: Install Python 3.12
          command: |
            set -euxo pipefail
            choco feature enable -n allowGlobalConfirmation
            # skip python install if we already have something that's good enough
            if ! python --version | grep -q 'Python 3\.12'; then
              choco upgrade python312 --package-parameters="/NoLockdown"
            fi
            pip install pipenv

jobs:
  python-cache-dependencies:
    parameters:
      app-dir:
        type: string
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - python-install-pipenv-packages:
          app-dir: <<parameters.app-dir>>

workflows:
  build-and-test:
    jobs:
      - python-cache-dependencies:
          name: server cache dependencies linux
          app-dir: server
          executor: linux
      - python-cache-dependencies:
          name: server cache dependencies windows
          app-dir: server
          executor:
            name: windows/default
            shell: bash.exe
          pre-steps:
            - install-python-on-windows
```

Note: my GitHub repo contains a `server/` folder that contains a `Pipfile` and `Pipfile.lock` file (as well as the rest of my python code), hence the need for `app-dir: server` everywhere.

I think the fault arises because of a discrepancy between where a Windows bash command thinks `/tmp` is located within the Windows OS' filesystem, and where the CircleCI code handling the build instructions thinks `/tmp` is within the Windows OS' filesystem.

### PR DESCRIPTION
**Pull request by marboledacci**
Resolve #123 
The current directory to save the `python-cache` and `lockfile` file is /tmp. This causes problems on windows as the directory doesn't exist. I'm updating this to use a relative path instead so windows can find the files.

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:37acc908a946682a41d2bc4d7fddf44f0b1578ae

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:1fe33c82c29b16e9f116a1ff0f4567781a65bfa8

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:7df75697afe13ef32db56e0d204ccfeeacf7b808

**Review by david-montano-circleci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:bda4695471d263c10dcf1a73eddf190b4d082bac

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:bda4695471d263c10dcf1a73eddf190b4d082bac

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=3.0.0

**Comment by pcorpet** [comment]
Thanks for your contribution. Unfortunately adding the folder relatively makes them part of the app path which taints the current git repo. In my config I have now untracked files:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .cci_pycache/
        .temp-python-version
```

Do you think it would be possible to parametrize the temp folder so that it's possible to choose where it's stored?

**Comment by pcorpet** [comment]
> @pcorpet that should be possible, please create an issue so I can keep a better track of it.

Done in https://github.com/CircleCI-Public/python-orb/issues/127, thanks

**Pull request merged**
