### PR TITLE
fix: update save_cache step to use tmp python-version file

### LINKED ISSUE #99: Error saving and restoring pyenv cache from a machine executor
## Orb version:
`2.0.3`

## What happened:
```
error computing cache key: template: cacheKey:1:75: executing "cacheKey" at <checksum "/home/circleci/.pyenv/version">: error calling checksum: open /home/circleci/.pyenv/version: no such file or directory
```
image

## Expected behavior:

Cache is restored and saved correctly

## Additional Information:
Using executor machine
`ubuntu-2004:202111-02`

The `pyenv root` seems to be on `/opt/circleci/.pyenv` on this particular machine

### PR DESCRIPTION
**Pull request by Jaryt**
Fixes #99

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:b82ece81bbef38e93894ccc492da35e8ec7d615e

**Review by brivu — APPROVED** [review]
LGTM!

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:80b102d15bc9f02970a167a13f20a931fd4e9373

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:80b102d15bc9f02970a167a13f20a931fd4e9373

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=2.1.1

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:80b102d15bc9f02970a167a13f20a931fd4e9373

**Pull request merged**
