### PR TITLE
Clarify PEP621

### PR DESCRIPTION
**Pull request by LecrisUT**
Reading the implementation, this should work for PEP621 as well

### CODE REVIEW

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:d42b43a0ffb82854c36745a69f6c705e45cbbfd8

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:d42b43a0ffb82854c36745a69f6c705e45cbbfd8

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:e35a82ff9fc69fd9b85f06b0f805e7de68ae397c

**Comment by marboledacci** [comment]
The `pip-dist` alternative here is made to work in editable mode, so a setup.py file is required and it wouldn't work with just a `pyproject.toml `

**Comment by LecrisUT** [comment]
if you are referring to the failed tests, the issue is most likely:
```
WARNING: You are using pip version 19.2.3, however version 24.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:a5931e874c2fbf3ea4606b6259a6b239159901ec

**Review by marboledacci — APPROVED** [review]

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:daafb8979cdd1be30f1f4682bdcd2ab80f4e4ff1

**Comment by orb-publisher** [comment]
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=dev:daafb8979cdd1be30f1f4682bdcd2ab80f4e4ff1

**Comment by orb-publisher** [comment]
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/circleci/python?version=2.2.0

**Pull request merged**
