### PR TITLE
Cache ~/.local/bin when saving.

### PR DESCRIPTION
**Pull request by jaqx0r**
If you install a python command with pip, then you get back the library, and no command, and then "pip install --user foo" gives you odd failures where it claims foo is in fact installed! But you can't see ~/.local/bin/foo and you're tearing your hair out.

### Checklist

- [ x] All new jobs, commands, executors, parameters have descriptions
- [x ] Examples have been added for any significant new features
- [x ] README has been updated, if necessary

### Motivation, issues

If you install a python command with pip, then you get back the library, and no command, and then "pip install --user foo" gives you odd failures where it claims foo is in fact installed! But you can't see ~/.local/bin/foo and you're tearing your hair out.

### Description

Cache pip installed binaries as well as libraries to get a more complete record of the cached requirements.

### CODE REVIEW

**Comment by felicianotech** [comment]
My concern here is that `~/.local/bin/` is not a Python specific directory. If we automatically cache it in this orb's cache command, it may cache other items that might be there from other software. Do we want that? Can that cause a problem?

This actually also applies to the directory we're already caching, `~/.local/lib/`.

**Comment by jaqx0r** [comment]
Yeah, that's right. So the orb should really be fetching the install path
from pip and caching what pip thinks it has.

I don't know what that would take.  In the meantime, the orb is broken, and
I assume it's not being used for the case you suggest because of the
environment orbs apply to.

**Comment by jaqx0r** [comment]
Actually I think it'd be easy to do correctly: instead of saving
~/.local/{bin,lib}, have an intermediate step that copies out the full
manifest from pip into a temporary path or tarball, and cache that; and
reverse that for load-cache.

**Comment by jaqx0r** [comment]
I made us a bug to track this instead: #27

**Pull request merged**
